query GetUser(
  $filter: user_users_bool_exp
  $limit: Int
  $offset: Int
  $orderBy: [user_users_order_by!]
) {
  users: user_users(
    where: $filter
    limit: $limit
    offset: $offset
    order_by: $orderBy
  ) {
    status
    first_name
    last_name
    email
    id
    birth_date
    gender {
      gender_name
    }
    phone_number
    media {
      id
      url
    }
  }
}
